---
deployment:
  tasks:
    - export DEPLOYUSER=$USER
    - export DEPLOYPATH=/home/$DEPLOYUSER/public_html/
    - /bin/cp src/database.php $DEPLOYPATH
    - /bin/cp src/hello.php $DEPLOYPATH
    - /bin/cp src/index.php $DEPLOYPATH
    - /bin/cp src/phpinfo.php $DEPLOYPATH
    - /bin/cp src/.env.example $DEPLOYPATH
    - /bin/cp src/.htaccess.example $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R src/Utils $DEPLOYPATH
    - /bin/cp -R secrets $DEPLOYPATH
    - /bin/cp src/email.php $DEPLOYPATH
    - /bin/cp src/send_email.php $DEPLOYPATH
    - /bin/cp -R src/pagination $DEPLOYPATH
    - /bin/cp src/pagination.php $DEPLOYPATH
